--- 
  - name: Install percona server 5.7.44
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - /tmp/Percona-Server-shared-57-5.7.44-48.1.el7.x86_64.rpm
      - /tmp/Percona-Server-shared-compat-57-5.7.44-48.1.el7.x86_64.rpm
      - /tmp/Percona-Server-devel-57-5.7.44-48.1.el7.x86_64.rpm
      - /tmp/Percona-Server-client-57-5.7.44-48.1.el7.x86_64.rpm
      - /tmp/Percona-Server-server-57-5.7.44-48.1.el7.x86_64.rpm
    notify:
      - Disable mysqld auto start
  - meta: flush_handlers
